### ISSUE TITLE
Some weird stuff going on with the ampersands in the documentation.

### ISSUE THREAD

**Issue by Blanen** [SergiusIW/collider-rs#1]
I was looking through your docs and found that the ampersands on your docs have some weird stuff going on, have a look: 

http://i.imgur.com/pf3sCXJ.png

This is on chrome 53 on windows 8.

Also, I might be interested in contributing, as a rust learning experience, could there be some easy stuff I could help with maybe some time?

**Comment by SergiusIW** [comment]
Hi, thanks for reaching out!  As for the strange ampersand rendering in Chrome, the same seems to be the case for all rust docs, even for the standard library.  See this thread: https://github.com/rust-lang/rust/issues/24355.  The ampersands of course look fine in Firefox, and Mozilla developed both Firefox and Rust, so you can draw your own conclusions about their priorities :)

Thanks also for your offer to contribute.  However, I think there may be better ways for you to learn Rust, and I don't have any easy tasks to give you.  With the latest release of this library I am trying an experiment with the floating point arithmetic, so things are in a state of flux and uncertainty right now.  If you're interested, it would be helpful if you would try to use the library and provide feedback.  And if you have any ideas for new features, please feel free to suggest them or even to implement them and make a pull request.

If you are interested in game development with Rust, I recommend reading this series of posts: http://jadpole.github.io/arcaders/arcaders-1-0.

**Comment by Blanen** [comment]
Thanks for the response.

Interesting, and weird that they aren't fixing that...

I have this weird idea of creating a physics server that communicates with other parts through protobuf over unix sockets( Basically making a somewhat modular game server, I have never used any of these things... Might even not be useful) written in rust. So I might just use this lib sometime, yea.
