### ISSUE TITLE
Would Having a Collider Per Pixel Be Very Inefficient?

### ISSUE THREAD

**Issue by zicklag** [SergiusIW/collider-rs#15]
I was thinking of using this library to provide pixel-perfect collision detection for a game I was making. Would be be very inefiicient to literally create a hitbox for every pixel? I supposed that I could use an algorithm for creating larger square hitboxes for sprites and then using smaller ones around the edges to make sure that the sillouette is right, but it could still be a lot of hitboxes.

Would roughly 300,000 hit boxes be very inefficient?

**Comment by SergiusIW** [comment]
Hi, thanks for reaching out! I think it probably would be more inefficient than you would like. I would also advise against doing what you are suggesting regardless of whether you choose to use Collider or not. Games typically use polygons or circles as hitboxes, and such simple geometries may end up being more intuitive as well as more efficient. Even more sophisticated modern games use approximate geometries as hitboxes, see e.g. https://www.ssbwiki.com/Link_(SSBU)/Hitboxes . Good luck with your game development. God bless!

**Comment by zicklag** [comment]
Thanks so much for the response!

That makes sense. I'm working with what will typically low-resolution pixel games and I realized that I could probably leverage some bitsets to efficiently keep track of which pixels are occupied, and that I only ever need to to a check such as "does this sprite collide with another" instead of having the continuous collision detection.

Either way, this lib looks pretty neat and I might find another use for it some time 😉.

Blessings, and thanks again! :+1:
