### ISSUE TITLE
Collision point

### ISSUE THREAD

**Issue by whaqzhzd** [SergiusIW/collider-rs#5]
After the two HitBox collisions, I need to get the collision point. What should I do?

**Comment by SergiusIW** [comment]
I haven't made a collision point method. For my use cases so far, the [`PlacedShape::normal_from`](https://docs.rs/collider/0.3.0/collider/geom/struct.PlacedShape.html#method.normal_from) method has been enough. Though it would be easy enough to add a method like this. Here's what the function signature might look like:

```
impl PlacedShape {
  /// Returns the contact point of two shapes,
  /// or the nearest point if they are not overlapping
  fn contact_point(&self, other: &PlacedShape) -> Vec2 {...}
}
```

Let me know if this satisfies your use case. If so, I will add this method.

**Comment by whaqzhzd** [comment]
Returns the contact point of two shapes,or the nearest point if they are not overlapping。
Thank you very much. This is exactly what I need.
